### ISSUE TITLE
test chef cookbook in circleci fails

### ISSUE THREAD

**Issue by kyrylyuk-andriy** [test-kitchen/kitchen-dokken#160]
its a part of log where `kitchen converge` fails
```
....
Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-centos-7>
ssh: connect to host x.x.x.x port 32769: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```
my circleci config : 
```
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_integration

version: 2
jobs:      
  test_integration:
    docker:
      - image: chef/chefdk:2.5.4
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Integration test
          command: |
            export KITCHEN_YAML=.kitchen.dokken.yml
            chef exec bundle install
            chef exec rake test:integration
```

and my kitchen dokken config 

```
driver:
  name: dokken
  privileged: true
  chef_version: 13.8.5

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
    - recipe[my-cookbook::default]
```

version kitchen-dokken (2.6.7),

the same configuration  works on my laptop locally when i run `kitchen converge`
