### ISSUE TITLE
Dokken provisioner fails under concurrency

### ISSUE THREAD

**Issue by clintoncwolfe** [test-kitchen/kitchen-dokken#203]
## :ghost: Brief Description

While working with test-kitchen/test-kitchen#1677, which allows plugins to declare whether they are thread-safe, testing on my machine revealed that the dokken provisioner (which is really the chef-zero provisioner) may not be thread-safe.

## Version

Test kitchen 2.6.0
kitchen-dokken 2.10.0

## Environment

I'm running Mac OS Catalina

## Scenario

Run a 10-suite Kitchenfile with 5x concurrency reliably

## Steps to Reproduce

With the following Kitchenfile:
```
---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
verifier:
  name: inspec

suites:
  - name: vm-01
    run_list:
      - recipe[git]
  - name: vm-02
    run_list:
      - recipe[git]
  - name: vm-03
    run_list:
      - recipe[git]
  - name: vm-04
    run_list:
      - recipe[git]
  - name: vm-05
    run_list:
      - recipe[git]
  - name: vm-06
    run_list:
      - recipe[git]
  - name: vm-07
    run_list:
      - recipe[git]
  - name: vm-08
    run_list:
      - recipe[git]
  - name: vm-09
    run_list:
      - recipe[git]
  - name: vm-10
    run_list:
      - recipe[git]
```

and Berksfile:
```
source 'https://supermarket.chef.io'

cookbook 'git'
```

Run `kitchen test -c 5`

## Expected Result

Clean test on all ten instances

## Actual Result

Result varies a bit, but this is typical:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 6 actions failed.
>>>>>>     Failed to complete #converge action: [No such file or directory @ rb_sysopen - /Users/cwolfe/.dokken/kitchen_sandbox/c03478802c-vm-01-ubuntu-2004/validation.pem] on vm-01-ubuntu-2004
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - ip-10-0-22-2_us-east-2_compute_internal.crt] on vm-04-ubuntu-2004
>>>>>>     Failed to complete #converge action: [No such container: c03478802c-vm-05-ubuntu-2004
] on vm-05-ubuntu-2004
>>>>>>     Failed to complete #converge action: [No such container: c03478802c-vm-02-ubuntu-2004
] on vm-02-ubuntu-2004
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - ip-10-0-22-2_us-east-2_compute_internal.crt] on vm-08-ubuntu-2004
>>>>>>     Failed to complete #converge action: [No such file or directory @ rb_sysopen - /Users/cwolfe/.dokken/kitchen_sandbox/0e579a2d33-vm-09-ubuntu-2004/validation.pem] on vm-09-ubuntu-2004
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## :heavy_plus_sign: Additional context

It is possible that the problem is not with the dokken provisioner, but with the ChefZero provisioner it inherits from. However, I tested using kitchen-vagrant and ChefZero and found no problems - though that could just be that vagrant (which is a serialized driver) is too slow to trigger the race conditions.
