### ISSUE TITLE
misc DNS issues

### ISSUE THREAD

**Issue by dschlenk** [test-kitchen/kitchen-dokken#247]
## :speaking_head: Foreword

I'm new to using kitchen-dokken so the chances of this being PEBKAC is high, but I can't for the life of me get DNS to work via the default nameserver of 127.0.0.11.

## :ghost: Brief Description

I've tried overriding DNS with

```
platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      dns:
        - 192.168.65.1
```
in `.kitchen.yml`, but `/etc/resolv.conf` still has `127.0.0.11` as its only nameserver. If I manually alter `/etc/resolv.conf` to hit `192.168.65.1` instead, name resolution works. I also tried adding an `intermediate_instruction` of `- RUN echo "nameserver 192.168.65.1" > /etc/resolv.conf; echo "options ndots:0" >> /etc/resolv.conf` but that doesn't seem to be doing anything, likely due to the timing at which docker does things to `/etc/resolv.conf`? I'm new to docker, too.

## Version

2.14.0

## Environment

Latest Docker on macOS Catalina. I've turned off other virtualization software. 

## Scenario

Attempt to verify an old cookbook that uses serverspec for integration tests using kitchen-dokken instead of vagrant/virtualbox, but serverspec fails to install since DNS resolution does not work.

## Steps to Reproduce

Here's the parts of my kitchen yaml I changed with both attempted hacks in place:
```
---
driver:
  name: dokken
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      dns:
        - 192.168.65.1
      intermediate_instructions:
        - RUN echo "nameserver 192.168.65.1" > /etc/resolv.conf; echo "options ndots:0" >> /etc/resolv.conf
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

I run `kitchen verify [suite]-centos-7` and it converges properly but when it goes to install serverspec I get this:

```
       Finished converging <firewall-only-centos-7> (0m16.94s).
-----> Setting up <firewall-only-centos-7>...
       Finished setting up <firewall-only-centos-7> (0m0.00s).
-----> Verifying <firewall-only-centos-7>...
       Creating kitchen sandbox in /Users/schlazor/.dokken/verifier_sandbox/96169cff0b-firewall-only-centos-7
-----> Installing Busser (busser)
ERROR:  Could not find a valid gem 'busser' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)
sh: line 22: /opt/verifier/bin/busser: No such file or directory
-----> Installing Busser plugin: busser-serverspec
sh: line 29: /opt/verifier/bin/busser: No such file or directory
```

and if I log into the instance `/etc/resolv.conf` has

```
nameserver 127.0.0.11
options ndots:0
```

if I hand edit that to point to 192.168.65.1, then it works. But that's not particularly helpful in CI. I assume there's something wrong with my Docker setup, maybe it's a macOS thing. 

## Expected Result

ability to change `/etc/resolv.conf` via `dns` setting

## Actual Result

Unable to manipulate `/etc/resolv.conf` via `dns` setting and therefore name resolution fails

## :heavy_plus_sign: Additional context

Thanks for reading my rambling bug report that is surely user error.
