### ISSUE TITLE
Support for Windows images

### ISSUE THREAD

**Issue by ValkyrieOps** [test-kitchen/kitchen-dokken#275]
## Problem Statement

While Linux containers appear to be supported on Windows hosts, it does not seem like actual Windows containers are supported as part of the project (unless I've done something horribly wrong).  It would be great to spin up an instance of Windows Server/Core/Nano to test Windows deployments.

## Possible Solution

The main issue I believe is that the chef/chef image doesn't have a Windows variant and I'm not sure how to work around that.  

`Failed to complete #create action: [{"message":"no such image: chef/chef:latest: No such image: chef/chef:latest"}`

Here is my kitchen.yml that I would expect to work

```
driver:
  name: dokken

provisioner:
  name: chef_zero
  download_url: http://downloads.cinc.sh/files/stable/cinc/17.9.52/windows/2012r2/cinc-17.9.52-1-x64.msi
  product_name: <%= ENV['CHEF_PRODUCT_NAME'] || 'cinc' %>
  deprecations_as_errors: true
  chef_license: accept-no-persist

transport:
  name: dokken

verifier:
  name: inspec
  
platforms:
  - name: windows
    driver_config:
      image: mcr.microsoft.com/windows/servercore:ltsc2019

suites:
- name: default
  run_list:
    - recipe[my_nifty_windows_recipe]
```

## Alternatives

Vagrant/Hyper-V is extremely slow, and in my experience failed pipelines are unable to cleanup test kitchen due to inability to delete existing VMs/.VHD files.
