### ISSUE TITLE
figure out Gitlab CI

### ISSUE THREAD

**Issue by someara** [test-kitchen/kitchen-dokken#79]
I've received reports this doesn't work out of the box.
Making this issue to remind myself to track it down.

-s

**Comment by bdwyertech** [comment]
This is what I've got that seems to get almost there, the test suites don't seem to have access to `/opt/kitchen` though

```yaml
variables:
  DOCKER_HOST: tcp://docker:2375

  services:
    - docker:dind

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/chef exec gem list kitchen-dokken -q

test:ChefDK:
  image: chef/chefdk:current
  script:
    - chef exec delivery local lint
    - chef exec delivery local syntax
    - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify default -l debug
  tags:
    - chefdk
```

```yaml
---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

#
# => Platforms
#
platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install lsof initscripts net-tools selinux-policy-targeted systemd-sysv wget which

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

#
# => Test Suites
#
suites:
  - name: 'default'
    run_list:
      - recipe[nginx::default]
    # verifier:
    #   inspec_tests:
    #     - test/integration/default
    attributes:
      passenger:
       enabled: false
    includes: [
      'centos-7',
      'ubuntu-16.04'
    ]
```

**Comment by bdwyertech** [comment]
Debug log output:
```
BD-MBPro:nginxw bdwyer$ bin/gitlab_ci_test.sh
WARNING: You most probably have uncommitted changes.
WARNING: These changes will not be tested.
Running with gitlab-ci-multi-runner 1.11.0 (33af6569)
  on  ()
Using Docker executor with image chef/chefdk:current ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Waiting for services to be up and running...
Pulling docker image chef/chefdk:current ...
Running on runner--project-1-concurrent-0 via BD-MBPro.local...
Cloning repository...
Cloning into '/builds/project-1'...
done.
Checking out 73f9081c as fix-ci...
Skipping Git submodules setup
Checking cache for test:ChefDK/fix-ci...
Successfully extracted cache
$ eval "$(/opt/chefdk/bin/chef shell-init bash)"
$ /opt/chefdk/embedded/bin/chef --version
Chef Development Kit Version: 1.3.21
chef-client version: 12.19.36
delivery version: master (f73518976ad7c23d506232239a46cd50a3e04a36)
berks version: 5.6.3
kitchen version: 1.16.0
$ /opt/chefdk/embedded/bin/cookstyle --version
Cookstyle 1.3.0
  * RuboCop 0.47.1
$ /opt/chefdk/embedded/bin/foodcritic --version
foodcritic 9.0.0
$ /opt/chefdk/embedded/bin/chef exec gem list kitchen-dokken -q
kitchen-dokken (2.1.2)

$ chef exec delivery local lint
Chef Delivery
Running Lint Phase
Inspecting 35 files
...................................

35 files inspected, no offenses detected
$ chef exec delivery local syntax
Chef Delivery
Running Syntax Phase
Checking 33 files
.................................

$ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify default -l debug
-----> Starting Kitchen (v1.16.0)
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 library loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
D      Berksfile found at /builds/project-1/Berksfile, loading Berkshelf
D      Berkshelf 5.6.3 previously loaded
-----> Creating <default-centos-7>...
D      driver - pulling chef/chef:current centos 7
D      driver - pulling chef/chef:current chef/chef current
D      driver - creating volume container chef-current from chef/chef:current
       Creating kitchen sandbox at /root/.dokken/kitchen_sandbox/a9a387ea46-default-centos-7
       Creating verifier sandbox at /root/.dokken/verifier_sandbox/a9a387ea46-default-centos-7
D      driver - calling create_data_image
D      driver - creating a9a387ea46-default-centos-7-data
       Building work image..
D      driver - starting a9a387ea46-default-centos-7
       Finished creating <default-centos-7> (3m12.33s).
-----> Converging <default-centos-7>...
       Creating kitchen sandbox in /root/.dokken/kitchen_sandbox/a9a387ea46-default-centos-7
       Preparing dna.json
D      Creating dna.json from {:passenger=>{:enabled=>false}, :run_list=>["recipe[nginxw::default]"]}
       Resolving cookbook dependencies with Berkshelf 5.6.3...
D      Using Berksfile from /builds/project-1/Berksfile
       Removing non-cookbook files before transfer
       Preparing validation.pem
D      Using a dummy validation.pem
       Preparing client.rb
D      Creating client.rb from {:node_name=>"default-centos-7", :checksum_path=>"/opt/kitchen/checksums", :file_cache_path=>"/opt/kitchen/cache", :file_backup_path=>"/opt/kitchen/backup", :cookbook_path=>["/opt/kitchen/cookbooks", "/opt/kitchen/site-cookbooks"], :data_bag_path=>"/opt/kitchen/data_bags", :environment_path=>"/opt/kitchen/environments", :node_path=>"/opt/kitchen/nodes", :role_path=>"/opt/kitchen/roles", :client_path=>"/opt/kitchen/clients", :user_path=>"/opt/kitchen/users", :validation_key=>"/opt/kitchen/validation.pem", :client_key=>"/opt/kitchen/client.pem", :chef_server_url=>"http://127.0.0.1:8889", :encrypted_data_bag_secret=>"/opt/kitchen/encrypted_data_bag_secret", :treat_deprecation_warnings_as_errors=>false, :named_run_list=>{}}
[2017-03-09T16:31:31+00:00] WARN: *****************************************
[2017-03-09T16:31:31+00:00] WARN: Did not find config file: /opt/kitchen/client.rb, using command line options.
[2017-03-09T16:31:31+00:00] WARN: *****************************************
[2017-03-09T16:31:31+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /.
[2017-03-09T16:31:31+00:00] FATAL: Cannot load configuration from /opt/kitchen/dna.json
```

**Comment by someara** [comment]
Can you throw a "chef gem install kitchen-dokken" into your script to make
sure you're grabbing the latest driver?

ChefDK is quite a ways behind... still on the 1.x version.

-s

**Comment by someara** [comment]
Nevermind, I see you're on 2.1.2

**Comment by bdwyertech** [comment]
Yeah, it's pretty weird @someara , I'm thinking it's a Docker in Docker intricacy... Really seems like it's just not getting the volumes from the data image, which is weird, since it's totally tripping https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/driver/dokken.rb#L69

I'm gonna see if I can glean anything with a sleep statement after the kitchen build and checkout the environment with http://portainer.io/

**Comment by kevinreedy** [comment]
I've recreated the issue. https://gist.github.com/kevinreedy/51f0baa14e64b551b66110d7d30c037e

If I get some free time this week I'll try and get a fix in. @someara let me know if you want an account on my test GitLab setup.

**Comment by rmoriz** [comment]
Looks like missing volume mounts in the data container?

on the remote docker host:

```sh
$ docker exec -it  463855d9b6-asdf-debian-8-data find /opt
/opt
/opt/verifier
/opt/kitchen
```

**Comment by rmoriz** [comment]
Looks like the kitchen upload code was removed with 2.0.0 so remote docker setups are broken since that release.

**Comment by KovRon** [comment]
Hi everyone!
I have the same issue. I've tried several versions from 2.1.2 to 1.0.0 and in my case the issue gone only with 0.0.35 version.

**Comment by warroyo** [comment]
I was able to get this working using a gitlab runner with a docker executor. 

when setting up the executor you will need to mount a few volumes 

`--docker-volumes ~/.berkshelf:/root/.berkshelf  --docker-volumes /var/run/docker.sock:/var/run/docker.sock --docker-volumes /cache --docker-volumes ~/.dokken:/root/.dokken`

 this will allow the executor to leverage the hosts docker install(similar to running `--priviledged` on the runner). it also mounts the berkshelf directory in my case which holds my berkshelf config for my internal berks-api. lastly it mounts the ~/.dokken which is where the sandboxes are stored.

my kitchen config then just looks like this

````
---
driver:
  name: dokken
  chef_version: 12.20.3

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7.2
    driver:
     image: centos:7-systemd #this is a custom image
     pid_one_command: /usr/sbin/init
     privileged: true
suites:
  - name: default
    run_list:
      - recipe[test]
    attributes: {}
````
and the gitlab-ci.yml

````
stages:
  - test
variables:
  KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
lint:
  image: chef/chefdk
  tags:
    - docker-builds
  stage: test
  script:
    - cookstyle

test:
  image: chef/chefdk
  tags:
    - docker-builds
  stage: test
  script:
    - chef gem list | grep dokken
    - kitchen test --destroy always
````
DISCLAIMER:
I am not sure if I am doing this correctly or if any of this is bad practice. I have just started using dokken, so if anyone knows of any issues that may arise it would be great to know about them.

**Comment by aaronlippold** [comment]
Very interesting ...

**Comment by damacus** [comment]
I'm seeing a similar behaviour on CircleCI. 

In this case I think the answer might be to stop using docker-in-docker and fall back to the machine executor.

**Comment by tj-anderson** [comment]
I was looking at using Gitlab CI with a Docker-in-Docker runner and I was able to get kitchen-dokken working with a systemd cookbook I needed to test

I built the docker image to use and stored in my gitlab registry to speed up part of the process
Dockerfile
```
FROM docker:stable

RUN echo 'gem: --no-document' > $HOME/.gemrc \
    && apk update \
    && apk add build-base rsync git openssh libffi-dev ruby-dev ruby-bundler \
    && gem install kitchen-dokken kitchen-inspec berkshelf
```
Then my .gitlab-ci.yml
```
image: $CHEF_DIND_IMAGE

services:
  - docker:dind

before_script:
  - docker info

integration_test:
  stage: test
  script:
    - kitchen test
```
and  finally my .kitchen.yml
```
---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

#
# => Platforms
#
platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    
suites:
  - name: default
    run_list:
      - recipe[llm_postfix::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

**Comment by zedtux** [comment]
My working setup is this :

### .gitlab-ci.yml

```yaml
image: chef/chefdk

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:dind

rspec
  stage: test
  script:
    - rspec --color spec/unit/recipes

kitchen:debian-8
  stage: test
  script:
    - kitchen default-debian-8 test

kitchen:debian-9
  stage: test
  script:
    - kitchen default-debian-9 test
```

### .kitchen.yml

```yaml
---
driver:
  chef_version: latest # or 15 or 15.0 or 15.0.300 or curent
  name: dokken

transport:
  name: dokken

provisioner:
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept
  name: dokken

verifier:
  name: inspec

platforms:
  - name: debian-8
    driver:
      image: debian:8
  - name: debian-9
    driver:
      image: debian:9

suites:
  - name: default
    run_list:
      - recipe[docker-ce::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```
